# -*- coding: utf-8 -*-
"""labsheet4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R4QEH_NWCO002wabV7ey5naQEEMHLUPO
"""

# ============================================================
# EXPERIMENT NO. 4
# Advanced Data Visualization using Matplotlib and Seaborn
# Dataset: Netflix Movies and TV Shows
# ============================================================

# STEP 1: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Plot style
sns.set_theme(style="whitegrid")

# ============================================================
# STEP 2: Load Dataset
# ============================================================

df = pd.read_csv("netflix_titles.csv")

print("Dataset Loaded Successfully!")
print("\nFirst 5 Rows:")
print(df.head())

print("\nDataset Shape:", df.shape)

# ============================================================
# STEP 3: Basic Data Information
# ============================================================

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

# ============================================================
# STEP 4: Data Cleaning for Visualization
# ============================================================

# Fill missing values
df["country"] = df["country"].fillna("Unknown")
df["rating"] = df["rating"].fillna("Unknown")
df["director"] = df["director"].fillna("Unknown")
df["cast"] = df["cast"].fillna("Unknown")
df["date_added"] = df["date_added"].fillna("Unknown")

# Extract numeric duration
df["duration_num"] = df["duration"].str.extract(r"(\d+)").astype(float)

# ============================================================
# STEP 5: BAR CHART
# Compare Movies and TV Shows
# ============================================================

plt.figure(figsize=(8,5))

sns.countplot(data=df, x="type")

plt.title("Number of Movies and TV Shows on Netflix")
plt.xlabel("Content Type")
plt.ylabel("Number of Titles")

plt.show()

# ============================================================
# STEP 6: TOP 10 COUNTRIES BAR CHART
# ============================================================

country_count = (
    df["country"]
    .str.split(", ")
    .explode()
    .value_counts()
    .head(10)
)

plt.figure(figsize=(10,6))

sns.barplot(
    x=country_count.values,
    y=country_count.index
)

plt.title("Top 10 Countries by Netflix Titles")
plt.xlabel("Number of Titles")
plt.ylabel("Country")

plt.show()

# ============================================================
# STEP 7: LINE CHART
# Number of Netflix Titles Released Each Year
# ============================================================

year_count = df["release_year"].value_counts().sort_index()

plt.figure(figsize=(12,6))

plt.plot(
    year_count.index,
    year_count.values,
    marker="o"
)

plt.title("Netflix Titles Released by Year")
plt.xlabel("Release Year")
plt.ylabel("Number of Titles")

plt.show()

# ============================================================
# STEP 8: HISTOGRAM
# Distribution of Movie/Show Duration
# ============================================================

plt.figure(figsize=(10,6))

sns.histplot(
    data=df,
    x="duration_num",
    bins=30,
    kde=True
)

plt.title("Distribution of Netflix Content Duration")
plt.xlabel("Duration")
plt.ylabel("Frequency")

plt.show()

# ============================================================
# STEP 9: BOX PLOT
# Compare Duration of Movies and TV Shows
# ============================================================

plt.figure(figsize=(8,6))

sns.boxplot(
    data=df,
    x="type",
    y="duration_num"
)

plt.title("Duration Distribution by Content Type")
plt.xlabel("Content Type")
plt.ylabel("Duration")

plt.show()

# ============================================================
# STEP 10: SCATTER PLOT
# Release Year vs Duration
# ============================================================

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df,
    x="release_year",
    y="duration_num",
    hue="type",
    alpha=0.6
)

plt.title("Release Year vs Content Duration")
plt.xlabel("Release Year")
plt.ylabel("Duration")

plt.show()

# ============================================================
# STEP 11: TOP 10 RATINGS
# ============================================================

rating_count = df["rating"].value_counts().head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    x=rating_count.values,
    y=rating_count.index
)

plt.title("Top 10 Netflix Content Ratings")
plt.xlabel("Number of Titles")
plt.ylabel("Rating")

plt.show()

# ============================================================
# STEP 12: GENRE DISTRIBUTION
# ============================================================

genre_count = (
    df["listed_in"]
    .str.split(", ")
    .explode()
    .value_counts()
    .head(10)
)

plt.figure(figsize=(10,6))

sns.barplot(
    x=genre_count.values,
    y=genre_count.index
)

plt.title("Top 10 Netflix Genres")
plt.xlabel("Number of Titles")
plt.ylabel("Genre")

plt.show()

# ============================================================
# STEP 13: CORRELATION HEATMAP
# ============================================================

numeric_df = df[
    ["release_year", "duration_num"]
].dropna()

correlation = numeric_df.corr()

plt.figure(figsize=(7,5))

sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")

plt.show()

# ============================================================
# STEP 14: MULTIVARIATE VISUALIZATION
# ============================================================

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df,
    x="release_year",
    y="duration_num",
    hue="type",
    style="type",
    alpha=0.6
)

plt.title("Multivariate Analysis: Release Year, Duration and Type")
plt.xlabel("Release Year")
plt.ylabel("Duration")

plt.legend(title="Type")

plt.show()

# ============================================================
# STEP 15: BUSINESS INSIGHTS
# ============================================================

print("\n========== BUSINESS INSIGHTS ==========")

print("\n1. Content Type:")
print(df["type"].value_counts())

print("\n2. Most Common Rating:")
print(df["rating"].value_counts().head(1))

print("\n3. Most Common Release Year:")
print(df["release_year"].value_counts().head(1))

print("\n4. Top 5 Genres:")
print(genre_count.head(5))

print("\n5. Top 5 Countries:")
print(country_count.head(5))

# ============================================================
# STEP 16: SAVE ANALYSIS DATA
# ============================================================

df.to_csv("Netflix_Advanced_Visualization.csv", index=False)

print("\nAnalysis file saved as:")
print("Netflix_Advanced_Visualization.csv")


# ============================================================
# QUESTIONS & ANSWERS
# ============================================================

# Q1. Why is data visualization considered an essential component
# of data analytics?
#
# Answer:
# Data visualization converts complex data into graphical form.
# It helps identify trends, patterns, outliers and relationships
# easily and supports better decision-making.


# Q2. Differentiate between Matplotlib and Seaborn. Which library
# is more suitable for statistical visualizations and why?
#
# Answer:
# Matplotlib is a general-purpose visualization library and gives
# detailed control over plots.
# Seaborn is built on Matplotlib and provides attractive statistical
# plots with less code.
# Seaborn is generally more suitable for statistical visualizations
# because it works easily with Pandas data and provides statistical
# plots such as box plots, violin plots and heatmaps.


# Q3. Which type of chart would you choose to compare sales across
# different regions? Justify your answer.
#
# Answer:
# A bar chart is suitable because regions are categorical variables.
# It makes comparison between sales of different regions easy.


# Q4. What information can be obtained from a histogram and a
# box plot?
#
# Answer:
# A histogram shows the distribution, frequency and shape of
# numerical data.
# A box plot shows median, quartiles, spread and possible outliers.


# Q5. Explain the purpose of a scatter plot. How does it help in
# identifying relationships between variables?
#
# Answer:
# A scatter plot shows the relationship between two numerical
# variables. It helps identify positive correlation, negative
# correlation, patterns and outliers.


# Q6. What is a correlation heatmap? How can it assist in feature
# selection for machine learning?
#
# Answer:
# A correlation heatmap represents correlation values using colors.
# It helps identify strongly correlated features and can help detect
# redundant features during feature selection.


# Q7. Why is chart customization (titles, labels, legends, colors)
# important in data visualization?
#
# Answer:
# Customization improves readability and understanding.
# Titles explain the chart, labels identify variables, legends
# explain categories and colors help distinguish different groups.


# Q8. What factors should be considered while selecting an
# appropriate visualization for a dataset?
#
# Answer:
# The type of data, analytical objective, number of variables,
# audience, comparison requirement and relationship between
# variables should be considered.


# Q9. How can misleading visualizations affect business
# decision-making? Give a real-world example.
#
# Answer:
# Misleading scales, incorrect labels or inappropriate chart types
# can make small differences look very large.
# Example: A company may show a bar chart with a truncated Y-axis
# to make a small increase in sales appear extremely large,
# which can lead managers to make incorrect decisions.


# Q10. Explain how data visualization supports storytelling and
# business intelligence in organizations.
#
# Answer:
# Data visualization converts business data into understandable
# charts and dashboards. It helps organizations communicate trends,
# compare performance, identify problems and make data-driven
# decisions.