# -*- coding: utf-8 -*-
"""labsheet2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VwlrVSaB3MG5ongGfVWBKq8XrnEoNDA_
"""

# ============================================================
# EXPERIMENT NO. 2
# Exploratory Data Analysis (EDA) on a Real-World
# Business Dataset using Python
#
# Dataset: Netflix Movies and TV Shows
# ============================================================


# ------------------------------------------------------------
# 1. IMPORT REQUIRED LIBRARIES
# ------------------------------------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")
print("=" * 70)


# ------------------------------------------------------------
# 2. LOAD DATASET
# ------------------------------------------------------------

df = pd.read_csv("netflix_titles.csv")

print("Netflix dataset loaded successfully!")
print("=" * 70)


# ------------------------------------------------------------
# 3. BASIC DATASET EXPLORATION
# ------------------------------------------------------------

print("\nFIRST 5 ROWS:")
display(df.head())

print("\nDATASET SHAPE:")
print(df.shape)

print("\nCOLUMN NAMES:")
print(df.columns.tolist())

print("\nDATASET INFORMATION:")
df.info()

print("\nSTATISTICAL SUMMARY:")
display(df.describe(include="all"))


# ------------------------------------------------------------
# 4. CHECK MISSING VALUES
# ------------------------------------------------------------

print("\nMISSING VALUES:")
print(df.isnull().sum())


# ------------------------------------------------------------
# 5. CHECK DUPLICATES
# ------------------------------------------------------------

print("\nDUPLICATE RECORDS:")
print(df.duplicated().sum())


# ------------------------------------------------------------
# 6. VALUE COUNTS
# ------------------------------------------------------------

print("\nCONTENT TYPE:")
print(df["type"].value_counts())

print("\nTOP 10 COUNTRIES:")
print(df["country"].value_counts().head(10))

print("\nTOP 10 RATINGS:")
print(df["rating"].value_counts().head(10))


# ============================================================
# UNIVARIATE ANALYSIS
# ============================================================

# ------------------------------------------------------------
# 7. DISTRIBUTION OF RELEASE YEAR
# ------------------------------------------------------------

plt.figure(figsize=(10, 5))

sns.histplot(
    df["release_year"],
    bins=30,
    kde=True
)

plt.title("Distribution of Release Year")
plt.xlabel("Release Year")
plt.ylabel("Number of Titles")

plt.show()


# ------------------------------------------------------------
# 8. CONTENT TYPE COUNT PLOT
# ------------------------------------------------------------

plt.figure(figsize=(7, 5))

sns.countplot(
    data=df,
    x="type"
)

plt.title("Movies vs TV Shows")
plt.xlabel("Content Type")
plt.ylabel("Number of Titles")

plt.show()


# ------------------------------------------------------------
# 9. TOP 10 COUNTRIES
# ------------------------------------------------------------

top_countries = df["country"].value_counts().head(10)

plt.figure(figsize=(10, 6))

top_countries.plot(kind="bar")

plt.title("Top 10 Countries by Number of Netflix Titles")
plt.xlabel("Country")
plt.ylabel("Number of Titles")

plt.xticks(rotation=45)

plt.show()


# ------------------------------------------------------------
# 10. TOP 10 RATINGS
# ------------------------------------------------------------

top_ratings = df["rating"].value_counts().head(10)

plt.figure(figsize=(10, 5))

top_ratings.plot(kind="bar")

plt.title("Top Netflix Content Ratings")
plt.xlabel("Rating")
plt.ylabel("Number of Titles")

plt.xticks(rotation=45)

plt.show()


# ============================================================
# BIVARIATE ANALYSIS
# ============================================================

# ------------------------------------------------------------
# 11. MOVIES VS TV SHOWS BY RELEASE YEAR
# ------------------------------------------------------------

type_year = pd.crosstab(
    df["release_year"],
    df["type"]
)

type_year = type_year.tail(20)

type_year.plot(
    kind="bar",
    figsize=(12, 6)
)

plt.title("Movies and TV Shows by Release Year")
plt.xlabel("Release Year")
plt.ylabel("Number of Titles")

plt.xticks(rotation=45)

plt.show()


# ------------------------------------------------------------
# 12. RATING VS CONTENT TYPE
# ------------------------------------------------------------

plt.figure(figsize=(12, 6))

sns.countplot(
    data=df,
    x="rating",
    hue="type"
)

plt.title("Content Rating by Type")
plt.xlabel("Rating")
plt.ylabel("Number of Titles")

plt.xticks(rotation=45)

plt.show()


# ============================================================
# MULTIVARIATE ANALYSIS
# ============================================================

# ------------------------------------------------------------
# 13. CREATE NUMERICAL FEATURES
# ------------------------------------------------------------

# Extract first number from duration
df["duration_num"] = pd.to_numeric(
    df["duration"].str.extract(r"(\d+)")[0],
    errors="coerce"
)

# Encode content type
df["type_encoded"] = df["type"].map({
    "Movie": 0,
    "TV Show": 1
})

# Calculate number of days since release
df["content_age"] = 2025 - df["release_year"]


# ------------------------------------------------------------
# 14. CORRELATION MATRIX
# ------------------------------------------------------------

numeric_df = df[
    [
        "release_year",
        "duration_num",
        "type_encoded",
        "content_age"
    ]
].copy()

correlation = numeric_df.corr()

print("\nCORRELATION MATRIX:")
display(correlation)


# ------------------------------------------------------------
# 15. CORRELATION HEATMAP
# ------------------------------------------------------------

plt.figure(figsize=(8, 6))

sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")

plt.show()


# ------------------------------------------------------------
# 16. BOXPLOT
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x="type",
    y="duration_num"
)

plt.title("Duration Distribution by Content Type")
plt.xlabel("Content Type")
plt.ylabel("Duration")

plt.show()


# ------------------------------------------------------------
# 17. SCATTER PLOT
# ------------------------------------------------------------

plt.figure(figsize=(9, 6))

sns.scatterplot(
    data=df,
    x="release_year",
    y="duration_num",
    hue="type"
)

plt.title("Release Year vs Duration")
plt.xlabel("Release Year")
plt.ylabel("Duration")

plt.show()


# ============================================================
# ADDITIONAL BUSINESS INSIGHTS
# ============================================================

# ------------------------------------------------------------
# 18. YEAR WITH MOST CONTENT
# ------------------------------------------------------------

year_counts = df["release_year"].value_counts()

print("\nYEAR WITH MOST CONTENT:")
print(year_counts.head(10))


# ------------------------------------------------------------
# 19. MOVIE / TV SHOW TOTALS
# ------------------------------------------------------------

print("\nTOTAL MOVIES AND TV SHOWS:")
print(df["type"].value_counts())


# ------------------------------------------------------------
# 20. MOST COMMON GENRES
# ------------------------------------------------------------

genres = (
    df["listed_in"]
    .dropna()
    .str.split(", ")
    .explode()
)

print("\nTOP 10 GENRES:")
print(genres.value_counts().head(10))


# ------------------------------------------------------------
# 21. TOP DIRECTORS
# ------------------------------------------------------------

print("\nTOP 10 DIRECTORS:")
print(df["director"].value_counts().head(10))


# ------------------------------------------------------------
# 22. FINAL SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("EDA SUMMARY")
print("=" * 70)

print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

print("\nMost Common Content Type:")
print(df["type"].mode()[0])

print("\nMost Common Rating:")
print(df["rating"].mode()[0])

print("\nMost Common Genre:")
print(genres.mode()[0])

print("\nMost Common Country:")
print(df["country"].dropna().str.split(", ").explode().mode()[0])


# ============================================================
# SAVE EDA DATASET
# ============================================================

df.to_csv(
    "Netflix_EDA_Analysis.csv",
    index=False
)

print("\nEDA dataset saved successfully!")
print("File: Netflix_EDA_Analysis.csv")


# ============================================================
# QUESTIONS AND ANSWERS
# ============================================================


# Q1. What is Exploratory Data Analysis (EDA), and why is it
# performed before machine learning?
#
# Answer:
# EDA is the process of examining and visualizing a dataset
# to understand its structure, patterns, relationships and
# anomalies. It is performed before machine learning to identify
# data quality problems, understand important features and
# select suitable variables for model building.


# Q2. Differentiate between univariate, bivariate, and
# multivariate analysis with suitable examples.
#
# Answer:
#
# Univariate Analysis:
# Analysis of one variable.
# Example: Distribution of Netflix release years.
#
# Bivariate Analysis:
# Analysis of two variables.
# Example: Release year vs content type.
#
# Multivariate Analysis:
# Analysis of more than two variables.
# Example: Release year, duration and content type together.


# Q3. What insights can be obtained from a correlation heatmap?
#
# Answer:
# A correlation heatmap shows the strength and direction of
# relationships between numerical variables. Values close to
# +1 indicate strong positive correlation, values close to -1
# indicate strong negative correlation, and values near 0
# indicate weak or no linear relationship.


# Q4. Explain the purpose of histograms, box plots, and
# scatter plots in EDA.
#
# Answer:
#
# Histogram:
# Shows the distribution and frequency of numerical data.
#
# Box Plot:
# Shows median, spread and possible outliers.
#
# Scatter Plot:
# Shows the relationship between two numerical variables.


# Q5. How can EDA help identify data quality issues
# before analysis?
#
# Answer:
# EDA can identify missing values, duplicate records, outliers,
# incorrect data types, inconsistent categories and unusual
# distributions. This helps clean the dataset before further
# analysis or machine learning.


# Q6. Why is correlation important in predictive analytics?
# Can correlation imply causation?
#
# Answer:
# Correlation helps identify relationships between variables
# and can help in feature selection. However, correlation does
# not imply causation. Two variables may be correlated without
# one causing the other.


# Q7. Which visualization would you use to analyze categorical
# and numerical variables? Justify your choice.
#
# Answer:
#
# Categorical Variables:
# Bar charts and count plots are suitable because they show
# the frequency of different categories.
#
# Numerical Variables:
# Histograms, box plots and scatter plots are useful because
# they show distribution, outliers and relationships.


# Q8. What business insights can be derived from the Netflix
# dataset through EDA?
#
# Answer:
# EDA can identify:
# 1. The number of Movies and TV Shows.
# 2. Countries producing the most content.
# 3. Most common content ratings.
# 4. Popular genres.
# 5. Trends in content release over the years.
# These insights can support content planning and business
# decision-making.


# Q9. How does EDA contribute to feature selection
# and model building?
#
# Answer:
# EDA helps identify important variables, relationships,
# redundant features, outliers and unusual patterns.
# This helps analysts select useful features and prepare
# better inputs for machine learning models.


# Q10. What challenges might arise while performing EDA
# on large-scale real-world datasets?
#
# Answer:
# Major challenges include:
# 1. Large data size.
# 2. High processing and memory requirements.
# 3. Missing and inconsistent data.
# 4. Large number of features.
# 5. Slow visualization and computation.
# 6. Difficulty in identifying meaningful patterns.


# ============================================================
# END OF EXPERIMENT 2
# ============================================================