# -*- coding: utf-8 -*-
"""labsheet7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XNvyWmyaKtTLFyYlgis_XGoG0KYHe79
"""

# ============================================================
# EXPERIMENT 7
# Customer Segmentation using K-Means Clustering
# ============================================================

# -------------------- IMPORT LIBRARIES --------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# -------------------- UPLOAD DATASET --------------------
print("Upload Mall_Customers.csv")
uploaded = files.upload()

filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

print("\nDataset Loaded Successfully!")
print("File Name:", filename)

# -------------------- BASIC INFORMATION --------------------
print("\nFirst 5 Rows:")
display(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

# -------------------- CLEANING --------------------
df = df.drop_duplicates()
df = df.dropna()

print("\nAfter Cleaning:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# -------------------- SELECT FEATURES --------------------
# Mall Customers dataset ke important columns
age_col = None
income_col = None
score_col = None

for col in df.columns:
    col_lower = col.lower()

    if "age" in col_lower:
        age_col = col

    if "income" in col_lower:
        income_col = col

    if "spending" in col_lower and "score" in col_lower:
        score_col = col

print("\nDetected Columns:")
print("Age:", age_col)
print("Annual Income:", income_col)
print("Spending Score:", score_col)

# Check
if age_col is None or income_col is None or score_col is None:
    print("\nERROR: Required columns not found!")
    print("Available columns:", df.columns.tolist())
else:

    # -------------------- SELECT DATA --------------------
    X = df[[age_col, income_col, score_col]].copy()

    print("\nSelected Features:")
    display(X.head())

    # -------------------- FEATURE SCALING --------------------
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    print("\nFeature Scaling Completed.")

    # ========================================================
    # ELBOW METHOD
    # ========================================================

    inertia = []

    for k in range(2, 11):
        kmeans = KMeans(
            n_clusters=k,
            random_state=42,
            n_init=10
        )

        kmeans.fit(X_scaled)
        inertia.append(kmeans.inertia_)

    plt.figure(figsize=(8, 5))
    plt.plot(range(2, 11), inertia, marker='o')
    plt.xlabel("Number of Clusters (K)")
    plt.ylabel("Inertia")
    plt.title("Elbow Method")
    plt.grid(True)
    plt.show()

    # ========================================================
    # SILHOUETTE SCORE
    # ========================================================

    silhouette_scores = []

    for k in range(2, 11):

        kmeans = KMeans(
            n_clusters=k,
            random_state=42,
            n_init=10
        )

        labels = kmeans.fit_predict(X_scaled)

        score = silhouette_score(X_scaled, labels)
        silhouette_scores.append(score)

    plt.figure(figsize=(8, 5))
    plt.plot(range(2, 11), silhouette_scores, marker='o')
    plt.xlabel("Number of Clusters (K)")
    plt.ylabel("Silhouette Score")
    plt.title("Silhouette Score for Different K")
    plt.grid(True)
    plt.show()

    # Best K based on Silhouette Score
    best_k = range(2, 11)[np.argmax(silhouette_scores)]

    print("\nBest K based on Silhouette Score:", best_k)

    # ========================================================
    # APPLY K-MEANS
    # ========================================================

    kmeans_final = KMeans(
        n_clusters=best_k,
        random_state=42,
        n_init=10
    )

    df["Cluster"] = kmeans_final.fit_predict(X_scaled)

    final_score = silhouette_score(X_scaled, df["Cluster"])

    print("\nFinal Silhouette Score:", round(final_score, 4))

    # ========================================================
    # CLUSTER CENTERS
    # ========================================================

    centers_scaled = kmeans_final.cluster_centers_

    centers_original = scaler.inverse_transform(centers_scaled)

    centers_df = pd.DataFrame(
        centers_original,
        columns=[age_col, income_col, score_col]
    )

    centers_df.index.name = "Cluster"

    print("\nCluster Centers:")
    display(centers_df)

    # ========================================================
    # CLUSTER SIZE
    # ========================================================

    print("\nNumber of Customers in Each Cluster:")
    print(df["Cluster"].value_counts().sort_index())

    # ========================================================
    # CLUSTER VISUALIZATION
    # ========================================================

    plt.figure(figsize=(9, 6))

    sns.scatterplot(
        data=df,
        x=income_col,
        y=score_col,
        hue="Cluster",
        palette="tab10",
        s=100
    )

    plt.scatter(
        centers_df[income_col],
        centers_df[score_col],
        marker="X",
        s=250,
        color="black",
        label="Centroids"
    )

    plt.title("Customer Segmentation using K-Means")
    plt.xlabel("Annual Income")
    plt.ylabel("Spending Score")
    plt.legend()
    plt.grid(True)
    plt.show()

    # ========================================================
    # AGE VS SPENDING SCORE
    # ========================================================

    plt.figure(figsize=(9, 6))

    sns.scatterplot(
        data=df,
        x=age_col,
        y=score_col,
        hue="Cluster",
        palette="tab10",
        s=100
    )

    plt.title("Age vs Spending Score")
    plt.xlabel("Age")
    plt.ylabel("Spending Score")
    plt.grid(True)
    plt.show()

    # ========================================================
    # CLUSTER PROFILE
    # ========================================================

    print("\nCluster Profile:")

    cluster_profile = df.groupby("Cluster")[
        [age_col, income_col, score_col]
    ].mean()

    display(cluster_profile)

    # ========================================================
    # CLUSTER SIZE GRAPH
    # ========================================================

    plt.figure(figsize=(8, 5))

    df["Cluster"].value_counts().sort_index().plot(
        kind="bar"
    )

    plt.xlabel("Cluster")
    plt.ylabel("Number of Customers")
    plt.title("Number of Customers in Each Cluster")
    plt.xticks(rotation=0)
    plt.grid(axis="y")
    plt.show()

    # ========================================================
    # SAVE RESULT
    # ========================================================

    output_file = "Customer_Segmentation_KMeans.csv"

    df.to_csv(output_file, index=False)

    print("\nFinal dataset saved as:", output_file)

    # Download result
    files.download(output_file)

    # ========================================================
    # FINAL RESULT
    # ========================================================

    print("\n==============================================")
    print("EXPERIMENT COMPLETED SUCCESSFULLY")
    print("==============================================")

    print("Number of Clusters:", best_k)
    print("Silhouette Score:", round(final_score, 4))


# ============================================================
# QUESTIONS & ANSWERS
# ============================================================

# Q1. What is the difference between clustering and classification?
# Answer:
# Clustering is an unsupervised learning technique that groups
# similar data points without predefined labels.
# Classification is supervised learning where data is assigned
# to predefined classes using labelled training data.

# Q2. Explain the principle of K-Means clustering.
# Answer:
# K-Means divides data into K clusters.
# It assigns each data point to the nearest centroid and
# repeatedly updates the centroids until the clusters stabilize.

# Q3. Why is scaling important before applying K-Means?
# Answer:
# K-Means uses distance calculations.
# Scaling prevents features with larger numerical values from
# dominating the clustering process.

# Q4. What is the Elbow Method?
# Answer:
# The Elbow Method helps determine the suitable number of clusters.
# It plots K against inertia and the point where the decrease
# starts slowing down is considered the elbow point.

# Q5. What is Silhouette Score?
# Answer:
# Silhouette Score measures how well data points fit within
# their own cluster compared with other clusters.
# Higher values generally indicate better-separated clusters.

# Q6. Is K-Means supervised or unsupervised?
# Answer:
# K-Means is an unsupervised machine learning algorithm because
# it works without predefined class labels.

# Q7. Give four applications of clustering.
# Answer:
# 1. Customer segmentation
# 2. Image segmentation
# 3. Document grouping
# 4. Market analysis

# Q8. What are the limitations of K-Means?
# Answer:
# 1. K must be selected beforehand.
# 2. Sensitive to outliers.
# 3. Sensitive to initial centroids.
# 4. Works best for roughly spherical clusters.

# Q9. How can clustering help in marketing or customer retention?
# Answer:
# Clustering can divide customers into groups based on
# purchasing behaviour, income and spending patterns.
# Businesses can then create suitable offers and strategies
# for different customer groups.

# Q10. Compare K-Means with hierarchical clustering.
# Answer:
# K-Means directly divides data into a predefined number of clusters.
# Hierarchical clustering creates a tree-like structure of clusters.
# K-Means is generally faster for large datasets, while hierarchical
# clustering provides a dendrogram showing relationships between groups.